name: nuget-build

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]

permissions:
  contents: read
  id-token: write
  attestations: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PKG: artifacts/package.nupkg

    steps:

# ---------------- CHECKOUT ----------------

    - name: Checkout
      uses: actions/checkout@v6

# ---------------- .NET SETUP ----------------

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

# ---------------- BUILD ----------------

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Pack NuGet
      run: |
        dotnet pack -c Release --no-build -o artifacts
        mv artifacts/*.nupkg $PKG
        ls -lah artifacts

# ---------------- INSTALL TOOLS ----------------

    - name: Install cosign
      uses: sigstore/cosign-installer@v3

    # - name: Install syft
    #   uses: anchore/sbom-action/download-syft@v0

    - name: Install grype
      uses: anchore/scan-action/download-grype@v6

# ---------------- SIGN ARTIFACT ----------------

    - name: Sign package
      run: |
        cosign sign-blob \
          --yes \
          --bundle artifacts/sign.bundle.json \
          "$PKG"

# ---------------- VERIFY SIGNATURE ----------------

    - name: Verify package signature
      run: |
        cosign verify-blob \
          --bundle artifacts/sign.bundle.json \
          --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/nuget.yml@refs/heads/main" \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          "$PKG"

# ---------------- SBOM ----------------

    # - name: Generate SBOM
    #   run: |
    #     syft scan dir:. -o spdx-json > artifacts/sbom.json

# ---------------- SBOM ----------------

    - name: Install CycloneDX
      run: |
        dotnet tool install -g CycloneDX

    - name: Generate SBOM
      run: |
        mkdir -p artifacts

        ~/.dotnet/tools/dotnet-CycloneDX \
            -o artifacts \
            -fn sbom.json \
            -F json \
            -rs \
            -t \
            *.sln
        
        # cat artifacts/sbom.json

# ---------------- SBOM ATTESTATION ----------------

    - name: Attest SBOM
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest-blob \
          --yes \
          --bundle artifacts/sbom.bundle.json \
          --predicate artifacts/sbom.json \
          --type spdx \
          "$PKG"

# ---------------- VERIFY SBOM ----------------

    - name: Verify SBOM attestation
      run: |
        cosign verify-blob-attestation \
          --bundle artifacts/sbom.bundle.json \
          --type spdx \
          --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/nuget.yml@refs/heads/main" \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          "$PKG"

# ---------------- VULN SCAN ----------------

    - name: Scan vulnerabilities
      run: |
        grype sbom:artifacts/sbom.json -o json > artifacts/vuln.json

# ---------------- VULN ATTESTATION ----------------

    - name: Attest vulnerabilities
      run: |
        cosign attest-blob \
          --yes \
          --bundle artifacts/vuln.bundle.json \
          --predicate artifacts/vuln.json \
          --type vuln \
          "$PKG"

# ---------------- VERIFY VULN ----------------

    - name: Verify vulnerability attestation
      run: |
        cosign verify-blob-attestation \
          --bundle artifacts/vuln.bundle.json \
          --type vuln \
          --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/nuget.yml@refs/heads/main" \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          "$PKG"

# ---------------- PROVENANCE ----------------

    - name: Generate provenance
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: artifacts/package.nupkg

# ---------------- ARTIFACT UPLOAD ----------------

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: |
          artifacts/package.nupkg
          artifacts/*.json

# ---------------- PUBLISH ----------------

    - name: Add GitHub NuGet source
      run: |
        dotnet nuget add source \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github \
          https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Publish NuGet package
      run: |
        dotnet nuget push $PKG \
          --source github \
          --skip-duplicate